import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import AddProjectButton from "@/components/AddProjectButton";
import ProjectFeed from "@/components/projectFeed";
import Header from "@/components/Header";

const Projects: NextPage = () => {
  const { data: sessionData } = useSession();

  const title = sessionData ? `personal page` : "Sign in redirect";

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        {sessionData ? (
          <>
            <Header
              title={`${sessionData?.user.name}'s projects`}
              subtitle="These are your projects."
            />
            <div className="mb-4 flex justify-end">
              <AddProjectButton userId={sessionData?.user.id} />
            </div>
            {sessionData?.user.id && (
              <ProjectFeed userId={sessionData?.user.id} />
            )}
          </>
        ) : (
          <div>
            <Link href="/signin">
              <span>Sign in</span>
            </Link>
          </div>
        )}
      </div>
    </>
  );
};

export default Projects;
