import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import ProjectFeed from "@/components/projectFeed";

const Personal: NextPage = () => {
  const { data: sessionData } = useSession();

  const title = sessionData ? `personal page` : "Sign in redirect";

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        {sessionData ? (
          <>
            <h1 className="text-4xl font-normal tracking-tight">
              Welcome back <span>{sessionData?.user.name}</span>
            </h1>
            <p className="mt-2 text-lg text-foreground/60">
              This is your personal page.
            </p>
            <div className="mt-28 grid grid-cols-2 gap-12">
              <Card>
                <CardHeader>
                  <CardTitle>
                    <Link href="/personal/projects">Projects</Link>
                  </CardTitle>
                  <CardDescription>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  </CardDescription>
                </CardHeader>
                <CardContent className="flex flex-col gap-4">
                  {sessionData?.user.id && (
                    <ProjectFeed compact userId={sessionData?.user.id} />
                  )}
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Projects</CardTitle>
                </CardHeader>
              </Card>
            </div>
          </>
        ) : (
          <div>
            <Link href="/signin">
              <span>Sign in</span>
            </Link>
          </div>
        )}
      </main>
    </>
  );
};

export default Personal;
